name       : libphutil
version    : 5
release    : 1
source     :
    - git|https://github.com/phacility/libphutil.git : 5e14a5b17809be93c79554bc87bb5b6fe0f70bf4
license    : Apache-2.0
component  : programming.library
summary    : A collection of PHP utility classes
description: |
    A collection of PHP utility classes
rundeps    :
    - php
install    : |
    install -dm00644 $installdir/usr/share/php/libphutil/
    cp -R * $installdir/usr/share/php/libphutil/
    rm $installdir/usr/share/php/libphutil/{LICENSE,NOTICE,README.md}
