name       : libphutil
version    : 2019.09.04
release    : 3
source     :
    - git|https://github.com/phacility/libphutil.git : f51f1b3f72b50246949d0917239ca84f39ec7a54
license    : Apache-2.0
component  : programming.library
summary    : A collection of PHP utility classes
description: |
    A collection of PHP utility classes
rundeps    :
    - php
install    : |
    install -dm00644 $installdir/usr/share/php/libphutil/
    cp -R * $installdir/usr/share/php/libphutil/
    rm $installdir/usr/share/php/libphutil/{LICENSE,NOTICE,README.md}
